[profile.default]
src = "examples/solidity"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
ffi = true
solc_version = "0.8.33"
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./compiler/yul" }]

[rpc_endpoints]
